### ISSUE TITLE
Broken tutorial page

### ISSUE THREAD

**Issue by peterlamar** [dgraph-io/tutorial#39] opened 2018-06-18 14:08 UTC
https://tour.dgraph.io/schema/6/

This page appears broken? I receive this error:

{
  "errors": [
    {
      "code": "ErrorInvalidRequest",
      "message": "while lexing ...michael... <boss_of> ...someone... .: Invalid input: m at lexText"
    }
  ],
  "data": null
}

**Comment by paulftw** [comment] 2018-06-25 14:16
This exercise asks the user to substitute `...michael...` with the `uid` of Michael.
Closing as somewhat of a duplicate of #8.

**Closed by paulftw** 2018-06-25 14:16 UTC
